version: '3.8'

services:
  mysqldata-launcher:
    image: percona/percona-server:latest
    container_name: mysql_launcher_mysql
    ports:
      - 5576:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    volumes:
      - mysqldata-launcher:/var/lib/mysql

volumes:
  mysqldata-launcher: